# controllers:
#     resource: ../src/Controller/
#     type: attribute

index:
    path: /
    controller: App\Controller\ProyectoController::index
    
# index1:
#     path: /uno
#     controller: App\Controller\DefaultController::index1

# index2:
#     path: /dos
#     controller: App\Controller\DefaultController::index2

about:
  path: /about
  controller: App\Controller\DefaultController::about